### ISSUE TITLE
NoSuchMethodError upon executing Import Task

### ISSUE THREAD

**Issue by pbouillet** [herkne/buildship-import-4-oomph#1]
Hi,

I'm currently trying out the task but I get the error upon starting Eclipse:

```
java.lang.NoSuchMethodError: org.eclipse.buildship.core.launch.GradleRunConfigurationAttributes.with(Ljava/util/List;Ljava/lang/String;Lcom/gradleware/tooling/toolingclient/GradleDistribution;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;ZZ)Lorg/eclipse/buildship/core/launch/GradleRunConfigurationAttributes;
	at de.hkneissel.oomph.buildshipimport.impl.BuildshipImportTaskImpl$1.done(BuildshipImportTaskImpl.java:856)
	at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
	at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:106)
	at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:144)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:694)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:72)
```

Wanted to look at your code and correct it. But it seems like the repository version is out of sync with the code? Because line 856 does not match and I don't see a call to the .with method with these parameters.

**Comment by herkne** [comment]
Ok, you might be correct there - i think i haven't pushed my last changes.

But i would consider this project obsolete for some time now. 
The buildship project has improved very much over the last months/years and the standard project import in oomph now works well for buildship projects.

**Comment by pbouillet** [comment]
This might be true, but is there a replacement for executing a gradle task after the import is finished? Because this is what I need so much from your task.
